//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentC.WebUI.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int CarID { get; set; }
        public int CustomerID { get; set; }
        public byte ReservStatsID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Location { get; set; }
        public string CouponCode { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ReservationStatus ReservationStatus { get; set; }
    }
}
